import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Auth from "@/components/Auth";
import ProviderRedux from "@/libs/reduxStore/Provider";
import { cookies } from "next/headers";
import { UserProvider } from "@/libs/contexts/user.context";
import OrderProvider from "@/libs/contexts/order.context";
import DrawerProvider from "@/libs/contexts/drawerConfirm.context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Freelancer | Save and Secure",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const cookieStore = cookies();

  console.log('init value email', cookieStore.get('email')?.value);

  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <ProviderRedux>
          <UserProvider>
            <DrawerProvider>
              <OrderProvider>
                <Auth />
                <Header />
                {children}
                <Footer />
              </OrderProvider>
            </DrawerProvider>
          </UserProvider>
        </ProviderRedux>
      </body>
    </html>
  );
}
