import SearchTitle from "@/components/SearchTitle";
import {
  GetServerSideProps,
  GetServerSidePropsContext,
  GetStaticPaths,
  GetStaticProps,
  Metadata,
} from "next";
import React from "react";
import "../../styles/searchPage.scss";
import JobList from "@/components/JobList";

export const metadata: Metadata = {
  title: "Freelancer | Save and Secure",
  description: "Generated by create next app",
};
async function fetchSearchResults(query: string): Promise<any> {
  const res = await fetch(`http://your-api-endpoint/search?query=${query}`);
  return res.json();
}

const SearchPage = () => {
  return (
    <div className="searchPage">
      <SearchTitle />
      <JobList />
    </div>
  );
};

export default SearchPage;
