import SearchTitle from "@/components/SearchTitle";
import {
  GetServerSideProps,
  GetServerSidePropsContext,
  GetStaticPaths,
  GetStaticProps,
  Metadata,
} from "next";
import React from "react";
import "../../styles/searchPage.scss";
import JobList from "@/components/JobList";
import { ChakraProvider } from "@chakra-ui/react";
import SessionExpired from "@/components/SessionExpired";

export const metadata: Metadata = {
  title: "Freelancer | Save and Secure",
  description: "Generated by create next app",
};


const SearchPage = () => {
  return (
    <div className="searchPage">
      {/* <ChakraProvider>
        <SessionExpired />
      </ChakraProvider> */}
      <SearchTitle />
      <JobList />
    </div>
  );
};

export default SearchPage;
